version: 0.0
os: linux
files:
  - source: /
    destination: /usr/local/tomcat/webapps
permissions:
  - object: /
    pattern: 777
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStop:
    - location: stop_application.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: uninstall_war_file.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: start_application.sh
      timeout: 300
      runas: ec2-user
